spring.application.name=task-manager-api

# PostgreSQL datasource (ENV based)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# driver line remove kar di (Spring auto detect karega)

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=dGFza21hbmFnZXJfc3VwZXJfc2VjdXJlX3NlY3JldF9rZXlfMjAwMw==
jwt.expiration=36000000

server.forward-headers-strategy=NATIVE

# swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.persistAuthorization=true

logging.level.org.springframework.jdbc=DEBUG 