spring.application.name=task-manager-api

# MySQL Connection
spring.datasource.url=jdbc:mysql://root:wxvbznleJPxGJlkCZJlfIZZAApPTfzoO@shortline.proxy.rlwy.net:22080/task_manager_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=wxvbznleJPxGJlkCZJlfIZZAApPTfzoO

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=taskmanagersecurejwttokenkeytaskmanagersecurejwttokenkey123456
jwt.expiration=36000000
