spring.application.name=task-manager-api

# ===============================
# DATABASE (Supabase / Render ENV)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Supabase SSL REQUIRED
spring.datasource.hikari.data-source-properties.sslmode=require

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}
server.forward-headers-strategy=NATIVE

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=dGFza21hbmFnZXJfc3VwZXJfc2VjdXJlX3NlY3JldF9rZXlfMjAwMw==
jwt.expiration=36000000

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.persistAuthorization=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.jdbc=DEBUG